"""create_job_matches_and_applications

Revision ID: 4222f0a40203
Revises: af774e04d400
Create Date: 2026-09-24 14:31:47.325088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4222f0a40203'
down_revision: Union[str, Sequence[str], None] = 'af774e04d400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_profile_id', sa.String(length=36), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('overall_fit_verdict', sa.String(length=50), nullable=True),
    sa.Column('criteria_evaluations', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('potential_gaps', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_profile_id'], ['career_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_profile_id'), 'job_matches', ['profile_id'], unique=False)
    op.create_table('application_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('tailored_resume_markdown', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('short_proposal', sa.Text(), nullable=True),
    sa.Column('recruiter_message', sa.Text(), nullable=True),
    sa.Column('application_answers', sa.JSON(), nullable=True),
    sa.Column('portfolio_selection', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quality_review', sa.JSON(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_packages_job_id'), 'application_packages', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_packages_profile_id'), 'application_packages', ['profile_id'], unique=False)
    op.create_index(op.f('ix_application_packages_status'), 'application_packages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_packages_status'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_profile_id'), table_name='application_packages')
    op.drop_index(op.f('ix_application_packages_job_id'), table_name='application_packages')
    op.drop_table('application_packages')
    op.drop_index(op.f('ix_job_matches_profile_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
