"""add application tracking filter settings notifications and costs

Revision ID: 7d3a396da7eb
Revises: 4222f0a40203
Create Date: 2026-09-24 15:02:45.845379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3a396da7eb'
down_revision: Union[str, Sequence[str], None] = '4222f0a40203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=True),
    sa.Column('target_job_titles', sa.JSON(), nullable=True),
    sa.Column('target_categories', sa.JSON(), nullable=True),
    sa.Column('remote_types', sa.JSON(), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('min_salary', sa.String(length=50), nullable=True),
    sa.Column('max_job_age_days', sa.Integer(), nullable=True),
    sa.Column('min_relevance_score', sa.Float(), nullable=True),
    sa.Column('excluded_companies', sa.JSON(), nullable=True),
    sa.Column('excluded_keywords', sa.JSON(), nullable=True),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('auto_prep_promising', sa.Boolean(), nullable=True),
    sa.Column('notification_email', sa.String(length=200), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('in_app_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('application_packages', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('application_packages', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('application_packages', sa.Column('outcome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_packages', 'outcome')
    op.drop_column('application_packages', 'follow_up_date')
    op.drop_column('application_packages', 'applied_at')
    op.drop_table('in_app_notifications')
    op.drop_table('filter_settings')
    op.drop_table('cost_events')
    # ### end Alembic commands ###
